create table news_likes
(
    id                int8 generated by default as identity,
    news_id           int8,
    person_profile_id int8,
    primary key (id)
);

alter table if exists news_likes add constraint news_likes_id_fk foreign key (news_id) references person_news;
alter table if exists news_likes add constraint person_likes_id_fk foreign key (person_profile_id) references person_profile;