create table person_comment
(
    id                int8 generated by default as identity,
    comment_text      varchar(255),
    news_id           int8,
    person_profile_id int8,
    primary key (id)
);
create table person_news
(
    id                int8 generated by default as identity,
    picture           varchar(255),
    news_text         varchar(255),
    person_profile_id int8,
    primary key (id)
);
create table person_profile
(
    id         int8 generated by default as identity,
    birthdate  date,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    person_id  int8,
    primary key (id)
);
alter table if exists person_comment add constraint news_comment_id_fk foreign key (news_id) references person_news;
alter table if exists person_comment add constraint person_comment_id_fk foreign key (person_profile_id) references person_profile;
alter table if exists person_news add constraint person_news_id_fk foreign key (person_profile_id) references person_profile;